md "SE Palmeiras"	
md "CR Flamengo"	
md "Atletico Mineiro"	
md "Gremio FBPA"
md "Sao Paulo FC"	
md "Fluminense FC"	
md "SC Internacional"	
md "Santos FC"	
md "Athletico Paranaense"
md "SC Corinthians"	
md "RB Bragantino"	
md "Fortaleza EC"	
md "EC Bahia"	
md "Ceara SC"	
md "Cuiaba EC"	
md "Atletico Goianiense"	
md "America Mineiro"	
md "EC Juventude"	
md "Sport Recife"	
md "Chapecoense"	